name: NoVoidLoss
version: ${project.version}
description: ${project.description}
api-version: '1.15'
author: Karl Essinger (KarlofDuty)
website: http://karlofduty.com
main: com.karlofduty.NoVoidLoss.NoVoidLoss